name: MangaX
version: '${version}'
main: me.chimkenu.mangax.MangaX
api-version: '1.20'
commands:
  kit:
    description: kit selector and hotbar load out
  sommun:
    description: summons the entities
  truce:
    description: Truce with other players
  worlddata:
    description: Modify world data
